### ISSUE TITLE
 if (largestFeasible > 0) check is useless

### ISSUE THREAD

**Issue by errx** [stanford-futuredata/ASAP#4]
https://github.com/stanford-futuredata/ASAP/blob/24e95b2f76b213f1999b5f997beaa070519b1230/ASAP-optimized.js#L248

https://github.com/stanford-futuredata/ASAP/blob/24e95b2f76b213f1999b5f997beaa070519b1230/ASAP-optimized.js#L267

or there is a bug?

**Comment by kexinrong** [comment]
Thanks for pointing this out! It was a bug in the implementation, but it shouldn't really affect the results since the parameter was mostly for optimization. 

I pushed a [fix](https://github.com/stanford-futuredata/ASAP/commit/73fa14a400627ea04b052727f44c1d942eb9f17d) to the javascript and the python implementation. Please let me know if you have questions.
